export default {
  LOGIN: () => require('assets/login.png'),
  REGISTRATION: () => require('assets/registration.png'),
  USER_AVATAR: () => require('assets/user-avatar.png'),
  CHANGE_PASSWORD: () => require('assets/change_password.png'),
  DOG: () => require('assets/dog.png'),
  CAT_BLACK: () => require('assets/animalCategory/cat-b.png'),
  CAT_WHITE: () => require('assets/animalCategory/cat-w.png'),
  DOG_BLACK: () => require('assets/animalCategory/dog-b.png'),
  DOG_WHITE: () => require('assets/animalCategory/dog-w.png'),
  TURTLE_BLACK: () => require('assets/animalCategory/turtle-b.png'),
  TURTLE_WHITE: () => require('assets/animalCategory/turtle-w.png'),
  RABBIT_BLACK: () => require('assets/animalCategory/rabbit-b.png'),
  RABBIT_WHITE: () => require('assets/animalCategory/rabbit-w.png'),
  PIGEON_BLACK: () => require('assets/animalCategory/pigeon-b.png'),
  PIGEON_WHITE: () => require('assets/animalCategory/pigeon-w.png'),
  MALE_BLACK: () => require('assets/animalGender/male-b.png'),
  MALE_WHITE: () => require('assets/animalGender/male-w.png'),
  FEMALE_BLACK: () => require('assets/animalGender/female-b.png'),
  FEMALE_WHITE: () => require('assets/animalGender/female-w.png'),
  UNKNOWN_BLACK: () => require('assets/animalGender/unknown-b.png'),
  UNKNOWN_WHITE: () => require('assets/animalGender/unknown-w.png'),
};
