export default {
  REGISTRATION: 'Registration',
  LOGIN: 'Login',
  HOMEPAGE: 'Homepage',
  GLOBAL_LOADER: 'Global Loader',
  LOGIN_HISTORY: 'Login History',
  USER_PROFILE: 'User Profile',
  SETTINGS: 'Settings',
  PASSWORD_CHANGE: 'Password Change',
  FORGOT_PASSWORD: 'Forgot Password',
  USER_PROFILE_PREVIEW: 'User Profile Preview',
  ADD_ANNOUNCEMENT: 'Add Announcement',
  EDIT_ANNOUNCEMENT: 'Edit Announcement',
  MULTI_SELECT: 'Multi Select',
  ANNOUNCEMENT_PREVIEW: 'Announcement Preview',
};
