version: 2.1

jobs:
  code-style:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint tests
          command: yarn test:lint

workflows:
  findme-ci:
    jobs:
      - code-style
