export default {
  // FONT SIZE
  HEADING_EXTRA_LARGE: 24,
  HEADING_LARGE: 20,
  HEADING_MEDIUM: 18,
  HEADING_NORMAL: 16,
  HEADING_SMALL: 14,
  HEADING_EXTRA_SMALL: 11,

  // FONT WEIGHT
  HEADING_WEIGHT_BOLD: '700',
  HEADING_WEIGHT_SEMIBOLD: '600',
  HEADING_WEIGHT_MEDIUM: '500',
  HEADING_WEIGHT_REGULAR: '300',
};
